services:
  db:
    image: postgres:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: <%= ENV["DB_USERNAME"] %> 
      POSTGRES_PASSWORD: <%= ENV["DB_PASS"] %> 
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d calendar_myapp_development -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle install && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/calendar_myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/calendar_myapp/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
  bundle_data:
  node_modules:
